// Generated by designlang v7.0.0 — https://github.com/Manavarya09/design-extract
// Source: https://conduit.ai/
import SwiftUI

extension Color {
  init(hex: UInt32) {
    let r = Double((hex >> 16) & 0xFF) / 255
    let g = Double((hex >> 8) & 0xFF) / 255
    let b = Double(hex & 0xFF) / 255
    self.init(red: r, green: g, blue: b)
  }

  // MARK: Semantic
  static let actionPrimary = Color(hex: 0xC65F39)
  static let actionSecondary = Color(hex: 0xDD6B00)
  static let surfaceDefault = Color(hex: 0x050505)
  static let textBody = Color(hex: 0x000000)
}

extension CGFloat {
  // MARK: Primitive spacing
  static let spacingS0: CGFloat = 1
  static let spacingS1: CGFloat = 47
  static let spacingS2: CGFloat = 63
  static let spacingS3: CGFloat = 71
  static let spacingS4: CGFloat = 78
  static let spacingS5: CGFloat = 94
  static let spacingS6: CGFloat = 125
  static let spacingS7: CGFloat = 160
  static let spacingS8: CGFloat = 256
  static let spacingS9: CGFloat = 295
  static let spacingS10: CGFloat = 311
  static let spacingS11: CGFloat = 335
  static let spacingS12: CGFloat = 350
  static let spacingS13: CGFloat = 413

  // MARK: Primitive radius
  static let radiusR0: CGFloat = 3
  static let radiusR1: CGFloat = 8
  static let radiusR2: CGFloat = 11
  static let radiusR3: CGFloat = 16
  static let radiusR4: CGFloat = 20
  static let radiusR5: CGFloat = 24
  static let radiusR6: CGFloat = 39
  static let radiusR7: CGFloat = 100
}

// MARK: Primitive palette (for direct use)
extension Color {
  static let brandPrimary = Color(hex: 0xC65F39)
  static let brandSecondary = Color(hex: 0xDD6B00)
  static let neutralN100 = Color(hex: 0x11100F)
  static let neutralN200 = Color(hex: 0xFFFFFF)
  static let neutralN300 = Color(hex: 0x595859)
  static let neutralN400 = Color(hex: 0x000000)
  static let neutralN500 = Color(hex: 0xC0C0C0)
  static let neutralN600 = Color(hex: 0x4A4A4A)
  static let neutralN700 = Color(hex: 0x222222)
  static let neutralN800 = Color(hex: 0xE6E6E6)
  static let neutralN900 = Color(hex: 0xA1A1AA)
  static let neutralN1000 = Color(hex: 0xD9D9D9)
  static let neutralN1100 = Color(hex: 0xF5F5F5)
  static let neutralN1200 = Color(hex: 0x6B6B6B)
  static let neutralN1300 = Color(hex: 0x343434)
  static let backgroundBg0 = Color(hex: 0x050505)
  static let backgroundBg1 = Color(hex: 0xFFFFFF)
  static let backgroundBg2 = Color(hex: 0x6B6B6B)
  static let backgroundBg3 = Color(hex: 0xF7F7F7)
  static let backgroundBg4 = Color(hex: 0xF5F5F5)
  static let textText0 = Color(hex: 0x000000)
  static let textText1 = Color(hex: 0x11100F)
  static let textText2 = Color(hex: 0x4A4A4A)
  static let textText3 = Color(hex: 0xFFFFFF)
  static let textText4 = Color(hex: 0x595859)
  static let textText5 = Color(hex: 0xBFBFBF)
  static let textText6 = Color(hex: 0x595959)
  static let textText7 = Color(hex: 0x050505)
  static let textText8 = Color(hex: 0xC65F39)
  static let textText9 = Color(hex: 0xF5F5F5)
}

// typography.body: family=Söhne size=70.5016px weight=400 lineHeight=77.5517px
