// Generated by designlang v7.0.0
// Source: https://conduit.ai/
import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Semantic
  static const Color actionPrimary = Color(0xFFC65F39);
  static const Color actionSecondary = Color(0xFFDD6B00);
  static const Color surfaceDefault = Color(0xFF050505);
  static const Color textBody = Color(0xFF000000);
  static const double spacingS0 = 1;
  static const double spacingS1 = 47;
  static const double spacingS2 = 63;
  static const double spacingS3 = 71;
  static const double spacingS4 = 78;
  static const double spacingS5 = 94;
  static const double spacingS6 = 125;
  static const double spacingS7 = 160;
  static const double spacingS8 = 256;
  static const double spacingS9 = 295;
  static const double spacingS10 = 311;
  static const double spacingS11 = 335;
  static const double spacingS12 = 350;
  static const double spacingS13 = 413;
  static const double radiusR0 = 3;
  static const double radiusR1 = 8;
  static const double radiusR2 = 11;
  static const double radiusR3 = 16;
  static const double radiusR4 = 20;
  static const double radiusR5 = 24;
  static const double radiusR6 = 39;
  static const double radiusR7 = 100;

  // Primitive palette
  static const Color brandPrimary = Color(0xFFC65F39);
  static const Color brandSecondary = Color(0xFFDD6B00);
  static const Color neutralN100 = Color(0xFF11100F);
  static const Color neutralN200 = Color(0xFFFFFFFF);
  static const Color neutralN300 = Color(0xFF595859);
  static const Color neutralN400 = Color(0xFF000000);
  static const Color neutralN500 = Color(0xFFC0C0C0);
  static const Color neutralN600 = Color(0xFF4A4A4A);
  static const Color neutralN700 = Color(0xFF222222);
  static const Color neutralN800 = Color(0xFFE6E6E6);
  static const Color neutralN900 = Color(0xFFA1A1AA);
  static const Color neutralN1000 = Color(0xFFD9D9D9);
  static const Color neutralN1100 = Color(0xFFF5F5F5);
  static const Color neutralN1200 = Color(0xFF6B6B6B);
  static const Color neutralN1300 = Color(0xFF343434);
  static const Color backgroundBg0 = Color(0xFF050505);
  static const Color backgroundBg1 = Color(0xFFFFFFFF);
  static const Color backgroundBg2 = Color(0xFF6B6B6B);
  static const Color backgroundBg3 = Color(0xFFF7F7F7);
  static const Color backgroundBg4 = Color(0xFFF5F5F5);
  static const Color textText0 = Color(0xFF000000);
  static const Color textText1 = Color(0xFF11100F);
  static const Color textText2 = Color(0xFF4A4A4A);
  static const Color textText3 = Color(0xFFFFFFFF);
  static const Color textText4 = Color(0xFF595859);
  static const Color textText5 = Color(0xFFBFBFBF);
  static const Color textText6 = Color(0xFF595959);
  static const Color textText7 = Color(0xFF050505);
  static const Color textText8 = Color(0xFFC65F39);
  static const Color textText9 = Color(0xFFF5F5F5);
}

ThemeData buildDesignlangTheme() {
  return ThemeData(
    colorScheme: const ColorScheme.light(
      primary: DesignTokens.actionPrimary,
      surface: DesignTokens.surfaceDefault,
    ),
  );
}
