// Generated by designlang v7.0.0
// Source: https://conduit.ai/
package com.designlang.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
    val ActionPrimary = Color(0xFFC65F39)
    val ActionSecondary = Color(0xFFDD6B00)
    val SurfaceDefault = Color(0xFF050505)
    val TextBody = Color(0xFF000000)
    val BrandPrimary = Color(0xFFC65F39)
    val BrandSecondary = Color(0xFFDD6B00)
    val NeutralN100 = Color(0xFF11100F)
    val NeutralN200 = Color(0xFFFFFFFF)
    val NeutralN300 = Color(0xFF595859)
    val NeutralN400 = Color(0xFF000000)
    val NeutralN500 = Color(0xFFC0C0C0)
    val NeutralN600 = Color(0xFF4A4A4A)
    val NeutralN700 = Color(0xFF222222)
    val NeutralN800 = Color(0xFFE6E6E6)
    val NeutralN900 = Color(0xFFA1A1AA)
    val NeutralN1000 = Color(0xFFD9D9D9)
    val NeutralN1100 = Color(0xFFF5F5F5)
    val NeutralN1200 = Color(0xFF6B6B6B)
    val NeutralN1300 = Color(0xFF343434)
    val BackgroundBg0 = Color(0xFF050505)
    val BackgroundBg1 = Color(0xFFFFFFFF)
    val BackgroundBg2 = Color(0xFF6B6B6B)
    val BackgroundBg3 = Color(0xFFF7F7F7)
    val BackgroundBg4 = Color(0xFFF5F5F5)
    val TextText0 = Color(0xFF000000)
    val TextText1 = Color(0xFF11100F)
    val TextText2 = Color(0xFF4A4A4A)
    val TextText3 = Color(0xFFFFFFFF)
    val TextText4 = Color(0xFF595859)
    val TextText5 = Color(0xFFBFBFBF)
    val TextText6 = Color(0xFF595959)
    val TextText7 = Color(0xFF050505)
    val TextText8 = Color(0xFFC65F39)
    val TextText9 = Color(0xFFF5F5F5)
    val SpacingS0 = 1.dp
    val SpacingS1 = 47.dp
    val SpacingS2 = 63.dp
    val SpacingS3 = 71.dp
    val SpacingS4 = 78.dp
    val SpacingS5 = 94.dp
    val SpacingS6 = 125.dp
    val SpacingS7 = 160.dp
    val SpacingS8 = 256.dp
    val SpacingS9 = 295.dp
    val SpacingS10 = 311.dp
    val SpacingS11 = 335.dp
    val SpacingS12 = 350.dp
    val SpacingS13 = 413.dp
    val RadiusR0 = 3.dp
    val RadiusR1 = 8.dp
    val RadiusR2 = 11.dp
    val RadiusR3 = 16.dp
    val RadiusR4 = 20.dp
    val RadiusR5 = 24.dp
    val RadiusR6 = 39.dp
    val RadiusR7 = 100.dp
}
